services:
  nginx:
    image: nginx
    ports:
      - 80:80
    volumes:
      - output_images:/data/images
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./static:/data/www:ro
  
  cardetect:
    image: gdezse/cardetect
    ports:
      - 5000:5000
    environment:
      - CARDETECT_OUTPUT_PATH=/usr/src/cardetect/output
    volumes:
      - output_images:/usr/src/cardetect/output
  
  rabbitmq:
    image: rabbitmq
    ports:
      - 5672:5672
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3
  
  admin-log:
    scale: 2
    image: gdezse/cardetect-admin
    environment:
      - EXCHANGE_NAME=detections
    depends_on:
      rabbitmq:
        condition: service_healthy

volumes:
  output_images: